const ADD_MEMBER = 'ADD_MEMBER';
const DELETE_MEMBER = 'DELETE_MEMBER';
const EDIT_MEMBER = 'EDIT_MEMBER';
const UPDATE_MEMBER = "UPDATE_MEMBER"
export {ADD_MEMBER, DELETE_MEMBER, EDIT_MEMBER, UPDATE_MEMBER}